AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  page-change-watcher-serverless
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  PageChangeWatcherFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          QUERY_URL: "https://google.com"
          QUERY_SELECTOR: 'input[value="Google Search"]'
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - app.ts

Outputs:
  PageChangeWatcherFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt PageChangeWatcherFunction.Arn
  PageChangeWatcherFunctionIamRole:
    Description: "IAM Role"
    Value: !GetAtt PageChangeWatcherFunctionRole.Arn
